# Generated by Django 4.2.7 on 2024-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmodel_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
