# Generated by Django 4.2.7 on 2024-04-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactmodel_tanggal_lahir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='tanggal_lahir',
        ),
    ]
